import pandas as pd
import numpy as np


def calculate_volume_profile(data, num_bins=100):
    """
    Calculates an approximate Volume Profile from OHLCV data.

    This function distributes each candle's volume across the price bins
    it overlaps with, approximating where trading activity occurred.

    Args:
        data: DataFrame with 'high', 'low', and 'volume' columns.
        num_bins (int): The number of price bins to create for the profile.

    Returns:
        pd.DataFrame: A DataFrame containing the volume profile with columns
                      'price_midpoint' and 'volume'.
    """

    # Determine the overall price range for the profile.
    min_price = data['low'].min()
    max_price = data['high'].max()

    # Create price points for the bins
    price_bins = np.linspace(min_price, max_price, num_bins + 1)

    # Initialize an array to hold the total volume for each bin.
    # The number of bins is one more than the number of price points.
    bin_volumes = np.zeros(num_bins)

    # Loop through each bin to calculate its total volume.
    for bin in range(num_bins):
        bin_lower_price = price_bins[bin]
        bin_upper_price = price_bins[bin+1]

        # Relevant candles are those with low below the top bin, and high above bottom bin
        relevant_candles = data[(data["low"] < bin_upper_price) & (data["high"] > bin_lower_price)]

        # If no candles overlap with this bin, skip to the next bin
        if relevant_candles.empty:
            continue
        
        # For each relevant candle, calculate how much the candle overlaps with the bin
        # To determine the proportion of volume to assign to the bin
        overlap_min = np.maximum(relevant_candles["low"], bin_lower_price)
        overlap_max = np.minimum(relevant_candles["high"], bin_upper_price)
        overlap_range = overlap_max - overlap_min
        candle_range = relevant_candles["high"] - relevant_candles["low"]
    
        # Avoid division by zero for flat candles (high == low)
        candle_range[candle_range == 0] = 1

        # Assign the volume to the bin based on the overlap proportion
        bin_volumes[bin] = np.sum(relevant_candles["volume"] * (overlap_range / candle_range))

    price_midpoint = (price_bins[:-1] + price_bins[bin + 1]) / 2

    volume_profile = pd.DataFrame({"price_midpoint": price_midpoint, 
                                   "volume": bin_volumes})
    
    return volume_profile


def find_significant_levels(volume_profile, prominence_factor = 1.5):
    """
    Identifies significant levels (POC, HVNs, LVNs) from a volume profile.
    
    Args:
        volume_profile: The DataFrame generated by calculate_volume_profile.
        prominence_factor (float): How much larger a peak's volume must be than the
                                   average to be considered a High Volume Node.

    Returns:
        dict: A dictionary containing the POC and lists of HVN/LVN prices.
    """
    # Point of Control (POC) is the price with the highest traded volume.
    poc_index = volume_profile["volume"].idxmax()
    poc = volume_profile.loc[poc_index].to_dict()

    # Calculate the average volume to identify what is "high" or "low".
    average_volume = volume_profile["volume"].mean()
    high_volume_bins = volume_profile[volume_profile["volume"] > (average_volume * prominence_factor)]
    low_volume_bins = volume_profile[volume_profile["volume"] < (average_volume / prominence_factor)]
    
    nodes = {"poc": poc,
             "high_volume_bins": high_volume_bins["price_midpoint"].to_list(),
             "low_volume_bins": low_volume_bins["price_midpoint"].to_list()}

    return nodes
